### ISSUE TITLE
Connection Leak in Campaign Summary 

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-platform#1042]
```
[debug] application - java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30000ms.
appcivist-plataform     | javax.persistence.PersistenceException: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30000ms.
appcivist-plataform     |   at com.avaje.ebeaninternal.server.transaction.TransactionManager.createQueryTransaction(TransactionManager.java:291)
appcivist-plataform     |   at com.avaje.ebeaninternal.server.core.DefaultServer.createQueryTransaction(DefaultServer.java:1956)
appcivist-plataform     |   at com.avaje.ebeaninternal.server.core.OrmQueryRequest.initTransIfRequired(OrmQueryRequest.java:169)
appcivist-plataform     |   at com.avaje.ebeaninternal.server.core.DefaultServer.findList(DefaultServer.java:1378)
appcivist-plataform     |   at com.avaje.ebeaninternal.server.core.DefaultServer.findUnique(DefaultServer.java:1180)
appcivist-plataform     |   at com.avaje.ebeaninternal.server.querydefn.DefaultOrmQuery.findUnique(DefaultOrmQuery.java:957)
appcivist-plataform     |   at com.avaje.ebeaninternal.util.DefaultExpressionList.findUnique(DefaultExpressionList.java:217)
appcivist-plataform     |   at models.Campaign.readByUUID(Campaign.java:878)
appcivist-plataform     |   at delegates.CampaignDelegate.getCampaignSummary(CampaignDelegate.java:172)
appcivist-plataform     |   at controllers.Campaigns.findCampaignByUUID(Campaigns.java:206)
appcivist-plataform     |   at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$320$$anonfun$apply$352.apply(Routes.scala:8548)
appcivist-plataform     |   at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$320$$anonfun$apply$352.apply(Routes.scala:8548)
appcivist-plataform     |   at play.core.routing.HandlerInvokerFactory$$anon$4.resultCall(HandlerInvoker.scala:136)
appcivist-plataform     |   at play.core.routing.HandlerInvokerFactory$JavaActionInvokerFactory$$anon$14$$anon$3$$anon$1.invocation(HandlerInvoker.scala:127)
appcivist-plataform     |   at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:70)
appcivist-plataform     |   at Global$ActionWrapper.call(Global.java:303)
appcivist-plataform     |   at http.Headers.call(Headers.java:11)
appcivist-plataform     |   at play.core.j.JavaAction$$anonfun$7.apply(JavaAction.scala:94)
appcivist-plataform     |   at play.core.j.JavaAction$$anonfun$7.apply(JavaAction.scala:94)
appcivist-plataform     |   at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
appcivist-plataform     |   at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
appcivist-plataform     |   at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:40)
appcivist-plataform     |   at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:70)
appcivist-plataform     |   at play.core.j.HttpExecutionContext.execute(HttpExecutionContext.scala:32)
appcivist-plataform     |   at scala.concurrent.impl.Future$.apply(Future.scala:31)
appcivist-plataform     |   at scala.concurrent.Future$.apply(Future.scala:492)
appcivist-plataform     |   at play.core.j.JavaAction.apply(JavaAction.scala:94)
appcivist-plataform     |   at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:105)
appcivist-plataform     |   at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:105)
appcivist-plataform     |   at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
appcivist-plataform     |   at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:104)
appcivist-plataform     |   at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:103)
appcivist-plataform     |   at scala.Option.map(Option.scala:146)
appcivist-plataform     |   at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:103)
appcivist-plataform     |   at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:96)
appcivist-plataform     |   at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:524)
appcivist-plataform     |   at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:524)
appcivist-plataform     |   at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:560)
appcivist-plataform     |   at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:560)
appcivist-plataform     |   at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$13.apply(Iteratee.scala:536)
appcivist-plataform     |   at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$13.apply(Iteratee.scala:536)
appcivist-plataform     |   at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
appcivist-plataform     |   at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
appcivist-plataform     |   at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
appcivist-plataform     |   at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
appcivist-plataform     |   at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
appcivist-plataform     |   at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
appcivist-plataform     |   at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
appcivist-plataform     |   at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
appcivist-plataform     | Caused by: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30000ms.
appcivist-plataform     |   at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:196)
appcivist-plataform     |   at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:147)
appcivist-plataform     |   at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:83)
appcivist-plataform     |   at play.db.ebean.DefaultEbeanConfig$EbeanConfigParser$WrappingDatasource.getConnection(DefaultEbeanConfig.java:138)
appcivist-plataform     |   at com.avaje.ebeaninternal.server.transaction.TransactionManager.createQueryTransaction(TransactionManager.java:273)
appcivist-plataform     |   ... 48 more
appcivist-plataform     | [error] application - 
appcivist-plataform     | 
appcivist-plataform     | ! @79fjihnbi - Internal server error, for (GET) [/api/user/534/notifications/stats] ->
appcivist-plataform     |  
appcivist-plataform     | play.api.UnexpectedException: Unexpected exception[PersistenceException: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30000ms.]
appcivist-plataform     |   at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:261)
appcivist-plataform     |   at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:191)
appcivist-plataform     |   at play.api.GlobalSettings$class.onError(GlobalSettings.scala:179)
appcivist-plataform     |   at play.core.j.JavaGlobalSettingsAdapter.play$core$j$JavaGlobalSettingsAdapter$$super$onError(JavaGlobalSettingsAdapter.scala:36)
appcivist-plataform     |   at play.core.j.JavaGlobalSettingsAdapter$$anonfun$onError$2.apply(JavaGlobalSettingsAdapter.scala:36)
appcivist-plataform     |   at play.core.j.JavaGlobalSettingsAdapter$$anonfun$onError$2.apply(JavaGlobalSettingsAdapter.scala:36)
appcivist-plataform     |   at scala.Option.getOrElse(Option.scala:121)
appcivist-plataform     |   at play.core.j.JavaGlobalSettingsAdapter.onError(JavaGlobalSettingsAdapter.scala:36)
appcivist-plataform     |   at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:94)
appcivist-plataform     |   at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$9$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:151)
appcivist-plataform     | Caused by: javax.persistence.PersistenceException: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30000ms.
appcivist-plataform     |   at com.avaje.ebeaninternal.server.transaction.TransactionManager.createQueryTransaction(TransactionManager.java:291)
appcivist-plataform     |   at com.avaje.ebeaninternal.server.core.DefaultServer.createQueryTransaction(DefaultServer.java:1956)
appcivist-plataform     |   at com.avaje.ebeaninternal.server.core.OrmQueryRequest.initTransIfRequired(OrmQueryRequest.java:169)
appcivist-plataform     |   at com.avaje.ebeaninternal.server.core.DefaultServer.findList(DefaultServer.java:1378)
appcivist-plataform     |   at com.avaje.ebeaninternal.server.querydefn.DefaultOrmQuery.findList(DefaultOrmQuery.java:939)
appcivist-plataform     |   at com.avaje.ebeaninternal.util.DefaultExpressionList.findList(DefaultExpressionList.java:197)
appcivist-plataform     |   at delegates.NotificationsDelegate.findNotificationsUser(NotificationsDelegate.java:1204)
appcivist-plataform     |   at controllers.Notifications.processUserNotificationSignalStats(Notifications.java:592)
appcivist-plataform     |   at controllers.Notifications.getNotificationSignalsStats(Notifications.java:581)
appcivist-plataform     |   at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$53$$anonfun$apply$85.apply(Routes.scala:6946)
appcivist-plataform     | Caused by: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30000ms.
appcivist-plataform     |   at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:196)
appcivist-plataform     |   at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:147)
appcivist-plataform     |   at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:83)
appcivist-plataform     |   at play.db.ebean.DefaultEbeanConfig$EbeanConfigParser$WrappingDatasource.getConnection(DefaultEbeanConfig.java:138)
appcivist-plataform     |   at com.avaje.ebeaninternal.server.transaction.TransactionManager.createQueryTransaction(TransactionManager.java:273)
appcivist-plataform     |   at com.avaje.ebeaninternal.server.core.DefaultServer.createQueryTransaction(DefaultServer.java:1956)
appcivist-plataform     |   at com.avaje.ebeaninternal.server.core.OrmQueryRequest.initTransIfRequired(OrmQueryRequest.java:169)
appcivist-plataform     |   at com.avaje.ebeaninternal.server.core.DefaultServer.findList(DefaultServer.java:1378)
appcivist-plataform     |   at com.avaje.ebeaninternal.server.querydefn.DefaultOrmQuery.findList(DefaultOrmQuery.java:939)
appcivist-plataform     |   at com.avaje.ebeaninternal.util.DefaultExpressionList.findList(DefaultExpressionList.java:197)
```

**Comment by cdparra** [comment]
This seems to be where the last leak occured: 
```
2018-10-07 16:42:38,876 [WARN] from com.zaxxer.hikari.pool.ProxyLeakTask in HikariPool-1 housekeeper - Connection leak detection triggered for org.postgresql.jdbc4.Jdbc4Connection@51c17a0a, stack trace follows
java.lang.Exception: Apparent connection leak detected
	at play.db.ebean.DefaultEbeanConfig$EbeanConfigParser$WrappingDatasource.getConnection(DefaultEbeanConfig.java:138)
	at com.avaje.ebeaninternal.server.transaction.TransactionManager.createTransaction(TransactionManager.java:243)
	at com.avaje.ebeaninternal.server.core.DefaultServer.createScopeTrans(DefaultServer.java:747)
	at com.avaje.ebeaninternal.server.core.DefaultServer.beginTransaction(DefaultServer.java:779)
	at com.avaje.ebeaninternal.server.core.DefaultServer.beginTransaction(DefaultServer.java:775)
	at com.avaje.ebean.Ebean.beginTransaction(Ebean.java:362)
	at controllers.Contributions.updateContribution(Contributions.java:2318)
	at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$209$$anonfun$apply$241.apply(Routes.scala:7882)
	at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$209$$anonfun$apply$241.apply(Routes.scala:7882)
	at play.core.routing.HandlerInvokerFactory$$anon$4.resultCall(HandlerInvoker.scala:136)
	at play.core.routing.HandlerInvokerFactory$JavaActionInvokerFactory$$anon$14$$anon$3$$anon$1.invocation(HandlerInvoker.scala:127)
	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:70)
	at Global$ActionWrapper.call(Global.java:303)
	at http.Headers.call(Headers.java:11)
	at be.objectify.deadbolt.java.actions.DynamicAction.lambda$applyRestriction$25(DynamicAction.java:75)
	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:106)
	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:106)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:40)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
2018-10-07 16:42:46,229 [WARN] from com.zaxxer.hikari.pool.ProxyLeakTask in HikariPool-1 housekeeper - Connection leak detection triggered for org.postgresql.jdbc4.Jdbc4Connection@3ae4a149, stack trace follows
java.lang.Exception: Apparent connection leak detected
	at play.db.ebean.DefaultEbeanConfig$EbeanConfigParser$WrappingDatasource.getConnection(DefaultEbeanConfig.java:138)
	at com.avaje.ebeaninternal.server.transaction.TransactionManager.createTransaction(TransactionManager.java:243)
	at com.avaje.ebeaninternal.server.core.DefaultServer.createScopeTrans(DefaultServer.java:747)
	at com.avaje.ebeaninternal.server.core.DefaultServer.beginTransaction(DefaultServer.java:779)
	at com.avaje.ebeaninternal.server.core.DefaultServer.beginTransaction(DefaultServer.java:775)
	at com.avaje.ebean.Ebean.beginTransaction(Ebean.java:362)
	at controllers.Contributions.updateContribution(Contributions.java:2318)
	at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$209$$anonfun$apply$241.apply(Routes.scala:7882)
	at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$209$$anonfun$apply$241.apply(Routes.scala:7882)
	at play.core.routing.HandlerInvokerFactory$$anon$4.resultCall(HandlerInvoker.scala:136)
	at play.core.routing.HandlerInvokerFactory$JavaActionInvokerFactory$$anon$14$$anon$3$$anon$1.invocation(HandlerInvoker.scala:127)
	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:70)
	at Global$ActionWrapper.call(Global.java:303)
```
