### ISSUE TITLE
Exception: Apparent connection leak detected

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-platform#1066]
https://sentry.io/social-apps-lab/appcivist-platform/issues/718213625/

```
Exception: Apparent connection leak detected
    at play.db.ebean.DefaultEbeanConfig$EbeanConfigParser$WrappingDatasource.getConnection(DefaultEbeanConfig.java:138)
    at com.avaje.ebeaninternal.server.transaction.TransactionManager.createQueryTransaction(TransactionManager.java:273)
    at com.avaje.ebeaninternal.server.core.DefaultServer.createQueryTransaction(DefaultServer.java:1956)
    at com.avaje.ebeaninternal.server.core.OrmQueryRequest.initTransIfRequired(OrmQueryRequest.java:169)
    at com.avaje.ebeaninternal.server.core.DefaultServer.findIterate(DefaultServer.java:1358)
...
(43 additional frame(s) were not displayed)

Connection leak detection triggered for org.postgresql.jdbc4.Jdbc4Connection@49a1eea2, stack trace follows
```

**Comment by yolile** [comment]
Already solved in develop
