### ISSUE TITLE
Bug in email sending for account verification

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-platform#41]
There is a bug in the email sending implementation used by play-authenticate. Even with the test gmail account we are using, configured with less secured parameters, the emails are not being sent through Gmail SMPT server. We might need to create and authenticate an AppCivist app in google's app engine

--- error details ---
[ERROR] [05/28/2015 13:24:09.455] [application-akka.actor.default-dispatcher-7] [TaskInvocation] Sending the email to the following server failed : smtp.gmail.com:465
org.apache.commons.mail.EmailException: Sending the email to the following server failed : smtp.gmail.com:465
	at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1410)
	at org.apache.commons.mail.Email.send(Email.java:1437)
	at com.typesafe.plugin.CommonsMailer.send(MailerPlugin.scala:398)
	at com.feth.play.module.mail.Mailer$MailJob.run(Mailer.java:422)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: javax.mail.AuthenticationFailedException: 534-5.7.14 <https://accounts.google.com/ContinueSignIn?sarp=1&scc=1&plt=AKgnsbujp
534-5.7.14 HPw6nWxT0GHcSbkfyfQ35TnexBy3fqcpWl1dB8TdeGgMHZ8W4s9aQ3y8U-g9Su3-IWIcW0
534-5.7.14 UmY-w6HyrJSXKiGYtOTFD2kFi0ECqqu5EC9N9kUImiOUSZKfZ3ZfOO1pQFZbiufDsMR1Ni
534-5.7.14 _86p0oFYBRhyVLg3VpYcS-3PIXbriaCI5eMKavqkNWCoQ8VO9HDSr3UgqQbPpDX5SIbqis
534-5.7.14 Z0eYvVt0sGNTUGCZRRmBSVA2fwUU> Please log in via your web browser and
534-5.7.14 then try again.
534-5.7.14 Learn more at
534 5.7.14 https://support.google.com/mail/bin/answer.py?answer=78754 q4sm3269832pdo.42 - gsmtp

	at com.sun.mail.smtp.SMTPTransport$Authenticator.authenticate(SMTPTransport.java:823)
	at com.sun.mail.smtp.SMTPTransport.authenticate(SMTPTransport.java:756)
	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:673)
	at javax.mail.Service.connect(Service.java:317)
	at javax.mail.Service.connect(Service.java:176)
	at javax.mail.Service.connect(Service.java:125)
	at javax.mail.Transport.send0(Transport.java:194)
	at javax.mail.Transport.send(Transport.java:124)
	at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1400)
	... 9 more

**Comment by cdparra** [comment]
In the meantime, i have hacked play-authenticate to not check if emails were validated/verified in authentication. This way, we can skip the "email verification" step for the moment, and still allow user signups

**Comment by cdparra** [comment]
Temporary fix: https://www.google.com/settings/security/lesssecureapps (turned ON for our test gmail account)

**Comment by cdparra** [comment]
SOURCE: http://stackoverflow.com/questions/25341198/javax-mail-authenticationfailedexception-is-thrown-while-sending-email-in-java
