### ISSUE TITLE
Errors in update of assembly

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-platform#639]
[debug] o.a.ebean.SUM - txn[2233] Updated [Assembly] [114]
== title == notifications.new_campaign.new.campaign
[info] application - NOTIFICATION: Creating notification EVENT  in notification service: http://localhost:3025/events---notifications.new_campaign.new.campaign
[info] o.a.ebean.TXN - txn[2233] Rollback
[error] application - Error updating assembly: java.net.ConnectException: Connection refused: localhost/127.0.0.1:3025
	at com.ning.http.client.providers.netty.request.NettyConnectListener.onFutureFailure(NettyConnectListener.java:128)
	at com.ning.http.client.providers.netty.request.NettyConnectListener.operationComplete(NettyConnectListener.java:140)
	at org.jboss.netty.channel.DefaultChannelFuture.notifyListener(DefaultChannelFuture.java:409)
	at org.jboss.netty.channel.DefaultChannelFuture.notifyListeners(DefaultChannelFuture.java:400)
	at org.jboss.netty.channel.DefaultChannelFuture.setFailure(DefaultChannelFuture.java:362)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:109)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:79)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:42)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: Connection refused: localhost/127.0.0.1:3025
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:716)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.connect(NioClientBoss.java:152)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:105)
	... 8 more

**Comment by loorely** [comment]
Check if these configurations exists on local.conf: 

```
notification{
            default {
                serverBaseUrl="http://127.0.0.1:8888",
                apiKey = "779ca795340d4b9582e18236e3613a1a6f1891f2482ba64d9494e421276ce889"
            }
        }
```

According to the stack trace, Subscription-manager should be running in [](http://localhost:3025/) 
Check and run project subscription-manager or update configuration accordingly.
