### ISSUE TITLE
Publish proposal null pointer exception in etherpad wrapper 

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-platform#805]
1. Open a WG
2. Find a draft proposal
3. Hit publish
nothing happens in ui, but in backend the following is seen

```
appcivist-plataform     | [debug] application - --> User authorization for assembly/ 111 is true
appcivist-plataform     | java.lang.NullPointerException
appcivist-plataform     | 	at net.gjerull.etherpad.client.EPLiteConnection.<init>(EPLiteConnection.java:56)
appcivist-plataform     | 	at net.gjerull.etherpad.client.EPLiteClient.<init>(EPLiteClient.java:37)
appcivist-plataform     | 	at utils.services.EtherpadWrapper.<init>(EtherpadWrapper.java:41)
appcivist-plataform     | 	at controllers.WorkingGroups.publishProposal(WorkingGroups.java:956)
appcivist-plataform     | 	at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$119$$anonfun$apply$151.apply(Routes.scala:7144)
appcivist-plataform     | 	at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$119$$anonfun$apply$151.apply(Routes.scala:7144)
appcivist-plataform     | 	at play.core.routing.HandlerInvokerFactory$$anon$4.resultCall(HandlerInvoker.scala:136)
appcivist-plataform     | 	at play.core.routing.HandlerInvokerFactory$JavaActionInvokerFactory$$anon$14$$anon$3$$anon$1.invocation(HandlerInvoker.scala:127)
appcivist-plataform     | 	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:70)
appcivist-plataform     | 	at Global$ActionWrapper.call(Global.java:303)
appcivist-plataform     | 	at http.Headers.call(Headers.java:11)
appcivist-plataform     | 	at be.objectify.deadbolt.java.actions.DynamicAction.lambda$applyRestriction$25(DynamicAction.java:75)
appcivist-plataform     | 	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:106)
appcivist-plataform     | 	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:106)
appcivist-plataform     | 	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
appcivist-plataform     | 	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249)
appcivist-plataform     | 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
appcivist-plataform     | 	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:40)
appcivist-plataform     | 	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
appcivist-plataform     | 	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
appcivist-plataform     | 	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
appcivist-plataform     | 	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
appcivist-plataform     | 	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
appcivist-plataform     | 	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by cdparra** [comment]
Pushed a patch in 13d757aaea286a9afff4e8a47bdc7a7002447400
It is not a final FIX, but will allow the update even if the null pointer exception happens.
