### ISSUE TITLE
Update password null pointer exception

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-platform#963]
To fix this, see comments below

```
c01c9f40ae3c_appcivist-plataform | [error] application - 
c01c9f40ae3c_appcivist-plataform | 
c01c9f40ae3c_appcivist-plataform | ! @78hgl9le1 - Internal server error, for (POST) [/api/user/password/change] ->
c01c9f40ae3c_appcivist-plataform |  
c01c9f40ae3c_appcivist-plataform | play.api.UnexpectedException: Unexpected exception[NullPointerException: null]
c01c9f40ae3c_appcivist-plataform | 	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:261) ~[com.typesafe.play.play_2.11-2.4.6.jar:2.4.6]
c01c9f40ae3c_appcivist-plataform | 	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:191) ~[com.typesafe.play.play_2.11-2.4.6.jar:2.4.6]
c01c9f40ae3c_appcivist-plataform | 	at play.api.GlobalSettings$class.onError(GlobalSettings.scala:179) [com.typesafe.play.play_2.11-2.4.6.jar:2.4.6]
c01c9f40ae3c_appcivist-plataform | 	at play.core.j.JavaGlobalSettingsAdapter.play$core$j$JavaGlobalSettingsAdapter$$super$onError(JavaGlobalSettingsAdapter.scala:36) [com.typesafe.play.play_2.11-2.4.6.jar:2.4.6]
c01c9f40ae3c_appcivist-plataform | 	at play.core.j.JavaGlobalSettingsAdapter$$anonfun$onError$2.apply(JavaGlobalSettingsAdapter.scala:36) [com.typesafe.play.play_2.11-2.4.6.jar:2.4.6]
c01c9f40ae3c_appcivist-plataform | 	at play.core.j.JavaGlobalSettingsAdapter$$anonfun$onError$2.apply(JavaGlobalSettingsAdapter.scala:36) [com.typesafe.play.play_2.11-2.4.6.jar:2.4.6]
c01c9f40ae3c_appcivist-plataform | 	at scala.Option.getOrElse(Option.scala:121) [org.scala-lang.scala-library-2.11.7.jar:na]
c01c9f40ae3c_appcivist-plataform | 	at play.core.j.JavaGlobalSettingsAdapter.onError(JavaGlobalSettingsAdapter.scala:36) [com.typesafe.play.play_2.11-2.4.6.jar:2.4.6]
c01c9f40ae3c_appcivist-plataform | 	at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:94) [com.typesafe.play.play_2.11-2.4.6.jar:2.4.6]
c01c9f40ae3c_appcivist-plataform | 	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:266) [com.typesafe.play.play-netty-server_2.11-2.4.6.jar:2.4.6]
c01c9f40ae3c_appcivist-plataform | Caused by: java.lang.NullPointerException: null
c01c9f40ae3c_appcivist-plataform | 	at controllers.Users.doChangePassword(Users.java:755) ~[appcivist-core.appcivist-core-0.1-SNAPSHOT.jar:1.5.2]
c01c9f40ae3c_appcivist-plataform | 	at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$42$$anonfun$apply$74.apply(Routes.scala:6844) ~[appcivist-core.appcivist-core-0.1-SNAPSHOT.jar:0.1-SNAPSHOT]
c01c9f40ae3c_appcivist-plataform | 	at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$42$$anonfun$apply$74.apply(Routes.scala:6844) ~[appcivist-core.appcivist-core-0.1-SNAPSHOT.jar:0.1-SNAPSHOT]
c01c9f40ae3c_appcivist-plataform | 	at play.core.routing.HandlerInvokerFactory$$anon$4.resultCall(HandlerInvoker.scala:136) ~[com.typesafe.play.play_2.11-2.4.6.jar:2.4.6]
c01c9f40ae3c_appcivist-plataform | 	at play.core.routing.HandlerInvokerFactory$JavaActionInvokerFactory$$anon$14$$anon$3$$anon$1.invocation(HandlerInvoker.scala:127) ~[com.typesafe.play.play_2.11-2.4.6.jar:2.4.6]
c01c9f40ae3c_appcivist-plataform | 	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:70) ~[com.typesafe.play.play_2.11-2.4.6.jar:2.4.6]
c01c9f40ae3c_appcivist-plataform | 	at Global$ActionWrapper.call(Global.java:303) ~[appcivist-core.appcivist-core-0.1-SNAPSHOT.jar:na]
c01c9f40ae3c_appcivist-plataform | 	at http.Headers.call(Headers.java:11) ~[appcivist-core.appcivist-core-0.1-SNAPSHOT.jar:0.1-SNAPSHOT]
c01c9f40ae3c_appcivist-plataform | 	at be.objectify.deadbolt.java.actions.RestrictAction.lambda$applyRestriction$35(RestrictAction.java:87) ~[be.objectify.deadbolt-java_2.11-2.4.0.jar:2.4.0]
c01c9f40ae3c_appcivist-plataform | 	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:106) ~[com.typesafe.play.play_2.11-2.4.6.jar:2.4.6]
```

**Comment by cdparra** [comment]
This is happening for users who signed up via an external authentication service and therefore have no `password` linked account. Add instead a return status 404 with the message: "This user used an external authentication service to sign in/sign up. Therefore, AppCivist cannot update the password"
